# Generated by Django 5.0.1 on 2024-01-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
            options={
                "verbose_name": "환자",
                "db_table": "patient",
            },
        ),
    ]
