# Generated by Django 5.0.1 on 2024-01-08 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="doctor",
            table="doctor",
        ),
    ]
